# Use Node for building
FROM node:18 AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code and build
COPY . .
RUN npm run build

# Use Nginx to serve the built files
FROM nginx:alpine

# Copy build files from previous stage
COPY --from=builder /app/dist /usr/share/nginx/html


# Copy custom Nginx config (optional)
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
