version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    container_name: terratrust-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://nifetemiboy:xeNNvtQYXJqMiYYY@cluster0.8rnguz2.mongodb.net/auth
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: terratrust-frontend
    ports:
      - "8080:80"
    depends_on:
      - server

volumes:
  mongo-data:
